--[[ ast/list.lua

  An object to represent lists.

  This is essentially a data object that holds parsed data and metadata related to lists.
  New list objects are generated by the parser (see parser.lua).

  Copyright (c) 2014, Joshua Ballanco.

  Licensed under the BSD 2-Clause License. See COPYING for full license details.

--]]


local list = {}

function list.new(car, cdr)
  local self = { type = "list" }
  self.car = car
  self.cdr = cdr
  return self
end

return list
